site_name: Swarms Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APAC Corp, Inc."
extra_css:
  - docs/assets/css/extra.css
extra:
  # analytics:
  #   provider: google
  #   property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: assets/img/SwarmsLogoIcon.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Swarms/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Swarms/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/img/SwarmsLogoIcon.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
    - Purpose: "purpose.md"
    - Roadmap: "roadmap.md"
    - Weaknesses: "failures.md"
    - Design: "design.md"
    - Flywheel: "flywheel.md"
    - Bounties: "bounties.md"
    - Metric: "metric.md"
    - Distribution: "distribution"
    - Research: "research.md"
    - Demos: "demos.md"
    - Architecture: "architecture.md"
    - Checklist: "checklist.md"
    - Hiring: "hiring.md"
- Swarms:
  - Overview: "swarms/index.md"
  - swarms.swarms:
    - AutoScaler: "swarms/swarms/autoscaler.md"
  - swarms.workers:
    - Overview: "swarms/workers/index.md"
    - AbstractWorker: "swarms/workers/abstract_worker.md"
  - swarms.agents:
    - AbstractAgent: "swarms/agents/abstract_agent.md"
    - OmniModalAgent: "swarms/agents/omni_agent.md"
  - swarms.models:
    - Overview: "swarms/models/index.md"
    - HuggingFaceLLM: "swarms/models/hf.md"
    - Anthropic: "swarms/models/anthropic.md"
  - swarms.structs:
    - Overview: "swarms/structs/overview.md"
    - Workflow: "swarms/structs/workflow.md"
    
- Examples:
    - Overview: "examples/index.md"
    - Agents:
      - OmniAgent: "examples/omni_agent.md"
- Applications:
    - CustomerSupport: 
      - Overview: "applications/customer_support.md"
    - Marketing: 
      - Overview: "applications/marketing_agencies.md" 
